Repository Laramus/Liberius, pull requests merged in 2023-10, with the labels that each got.

#9 rebase <feat>:views, rune, data
  app/controllers/Controller.php
  app/controllers/HomeController.php
  database/factory/dbfactory.php
  database/migrations/m_.php
  database/seeder/dbseeder.php
  public/css/global.css
  rune.struct
  rune/views/about.rune.php
  rune/views/index.rune.php
Labels: enhancement, hacktoberfest-accepted

#10 create route system
  app/Models/Model.php
  app/ancient/uri.php
  app/controllers/Controller.php
  app/controllers/HomeController.php
  package.json
  public/index.php
  route/routes.php
  rune/about.rune.php
  rune/index.rune.php
Labels: good first issue, hacktoberfest-accepted

#12 ;)
  app/ancient/uri.php
Labels: good first issue, hacktoberfest-accepted

#17 Update README.md
  README.md
Labels: good first issue, hacktoberfest-accepted

#19 create flash
  app/ancient/flasher.php
  app/controllers/Controller.php
  app/controllers/HomeController.php
  public/index.php
  rune/index.rune.php
Labels: hacktoberfest-accepted, worked

#21 update model
  .env
  app/Models/Model.php
  app/Models/User.php
  app/ancient/dbcon.php
  app/ancient/model.php
  app/controllers/Controller.php
  app/controllers/HomeController.php
Labels: hacktoberfest-accepted, worked

#22 DIRECTORY_SEPARATOR for route only
  routes/route.php
Labels: enhancement, hacktoberfest-accepted, worked

#23 create migration
  app/ancient/migration.php
  database/migrations/20231017094555_create_users_table.php
  database/migrations/m_.php
Labels: enhancement, hacktoberfest-accepted
